esphome:
  name: bl0942_test
  friendly_name: BL0942 Power Meter

esp8266:
  board: esp01_1m  # 根据你实际使用的板子修改，如 esp32dev

# Enable logging
logger:
  baud_rate: 0  # 禁用串口日志，避免冲突

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "BL0942 Fallback"
    password: "fallback_password"

captive_portal:

# ========== UART 配置（连接 BL0942 的 RX/TX） ==========
uart:
  id: uart1
  tx_pin: GPIO1   # 根据你接线调整
  rx_pin: GPIO3
  baud_rate: 4800
  stop_bits: 1

# ========== 引入 JuRudenko 的本地组件 ==========
external_components:
  - source:
      type: local
      path: ./custom_components

# ========== BL0942 传感器配置 ==========
sensor:
  - platform: bl0942
    uart_id: uart1
    voltage:
      name: "BL0942 Voltage"
      unit_of_measurement: "V"
      accuracy_decimals: 2
    current:
      name: "BL0942 Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
    power:
      name: "BL0942 Power"
      unit_of_measurement: "W"
      accuracy_decimals: 1
    energy:
      name: "BL0942 Energy"
      unit_of_measurement: "Wh"
      accuracy_decimals: 2
    frequency:
      name: "BL0942 Frequency"
    power_factor:
      name: "BL0942 Power Factor"
    apparent_power:
      name: "BL0942 Apparent Power"
    reactive_power:
      name: "BL0942 Reactive Power"
    gain_voltage: 1.0
    gain_current: 1.0
    gain_power: 1.0
    update_interval: 1s
